### PR TITLE
Reset file directory structure to match android plugin defaults

### PR DESCRIPTION
**Pull request by JBirdVegas**
This moves the following resources
./src -> ./src/main/java
./res -> ./src/main/res
./AndroidManifest.xml -> ./src/main/AndroidManifest.xml

This removes the need to declare non default locations in
the build.gradle

This breaks the ant builds. Tried a few things to fix the ant looking in the wrong place for the AndroidManifest.xml, either I'm declaring the values wrong or they are overridden somewhere.

### CODE REVIEW

**Comment by JBirdVegas** [comment]
@p4r4n01d do yo have a preference on the directory structure?  The basic idea was to match AS standard directories.

**Comment by p4r4n01d** [comment]
My only preference is to get this working: https://developer.android.com/sdk/installing/studio-androidview.html. There is also some more documentation here: http://developer.android.com/tools/studio/index.html#project-structure. I am guessing this is what you mean with AS standard directories though.

**Comment by p4r4n01d** [comment]
Also, can you organise activities and fragments into folders. FragmentActivities can go in a activity folder and fragments can go in a fragments folder.

**Comment by JBirdVegas** [comment]
The Android view appears to be loading as expected now.  Also organized the Fragments and Activities now the only class at the root package level is TheApplication.  Only problem right now is the tests are not running.  The android plugin added unit tests to the build recently [1] and since I've had to get it working for work I thought I might add some unit tests for us.  But sadly its not running during the test or check phases of the build.  I'll investigate why but I don't think unit tests should stop the merge.  We haven't ever had test before.

[1] http://tools.android.com/tech-docs/unit-testing-support

**Comment by JBirdVegas** [comment]
@p4r4n01d If I merge this now will it mess with your auth work?  This can wait if needed

**Comment by p4r4n01d** [comment]
My auth work will take a bit longer, so merge this if you have tested that
it works and I'll merge it (read: merge master) into my branch. I'll worry
about any problems then.

**Pull request merged**
